imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@AdministrationBundle/Resources/config/services.yml" }
    - { resource: "@CompanyBundle/Resources/config/services.yml" }
    - { resource: "@StoreBundle/Resources/config/services.yml" }
    - { resource: "@DeviceBundle/Resources/config/services.yml" }
    - { resource: "@DataCollectorBundle/Resources/config/services.yml" }
    - { resource: "@NotificationBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        #cookie_lifetime: 3600
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Propel Configuration
propel:
    dbal:
        driver:    %database_driver%
        user:       %database_user%
        password:   %database_password%
        dsn:        %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #spool:     { type: memory }
    spool:
        type: file
        path: "%kernel.root_dir%/data/mail-spool"

usoft_postcode:
    apiwise:
        key: 'P4YtqxfDFNlgy3nOt1tE4IC3w1uUbiv35fhgMpg0'