notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

data_collector:
    resource: "@DataCollectorBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /dashboard

datacollector:
    resource: "@DataCollectorBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

postcode:
    resource: "@UsoftPostcodeBundle/Resources/config/routing.yml"
    prefix:   /