data_collector:
    resource: "@DataCollectorBundle/Resources/config/routing.yml"
    prefix:   /

device:
    resource: "@DeviceBundle/Resources/config/routing.yml"
    prefix:   /

store:
    resource: "@StoreBundle/Resources/config/routing.yml"
    prefix:   /

company:
    resource: "@CompanyBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

postcode:
    resource: "@UsoftPostcodeBundle/Resources/config/routing.yml"
    prefix:   /