# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        UserBundle\Model\User:
            algorithm: bcrypt
            cost: 15

    providers:
        tcm_user_provider:
            propel:
                class: UserBundle\Model\User
                property: username
        chain_provider:
            chain:
                providers: [tcm_user_provider]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        tcm_area:
            pattern: ^/
            anonymous: ~
            simple_form:
                provider:             "tcm_user_provider"
                authenticator:        "tcm_authenticator"
                login_path:           /login
                check_path:           /login_verify
                default_target_path:  /
            logout:
                path:   /logout
                target: /

    access_control:
        - {path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/tcm, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_VIP_USER, ROLE_USER] }
        - {path: ^/logout, role: IS_AUTHENTICATED_FULLY }
        - {path: ^/administration, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

    access_denied_url: /login
