tcm_login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }
    options:
        expose: true

tcm_login_status:
    path:     /login_status
    methods:  [PUT]
    defaults: { _controller: UserBundle:Security:loginStatus }
    options:
        expose: true

login_verify:
    path:   /login_verify
    options:
        expose: true

logout:
    path:   /logout
