# TCM splash
tcm_splash:
    path:     /
    defaults: { _controller: AppBundle:Page:splash }
    options:
        expose: true

tcm_login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }
    options:
        expose: true

tcm_login_status:
    path:     /login_status
    methods:  [PUT]
    defaults: { _controller: UserBundle:Security:loginStatus }
    options:
        expose: true

tcm_profile_change_password:
    path:     /profile/change/password
    methods:  [POST]
    defaults: { _controller: UserBundle:Security:changePassword }
    options:
        expose: true

login_verify:
    path:   /login_verify
    options:
        expose: true

tcm_logout:
    path:   /logout
    options:
        expose: true
