tcm_dashboard:
    path:     /
    defaults: { _controller: AppBundle:Page:dashboard }
    options:
        expose: true

tcm_stores:
    path:     /stores
    defaults: { _controller: AppBundle:Page:stores }
    options:
        expose: true

tcm_stores_get:
    path:     /stores/get
    defaults: { _controller: AppBundle:Data:getStores }
    options:
        expose: true

tcm_store_get:
    path:     /store/{storeid}/get
    defaults: { _controller: AppBundle:Data:getStore }
    options:
        expose: true

tcm_store_show:
    path:     /store/{storeid}/show
    defaults: { _controller: AppBundle:Page:showStore }
    options:
        expose: true

tcm_store_inventory:
    path:     /store/{storeid}/inventory
    defaults: { _controller: AppBundle:Page:storeInventory }
    options:
        expose: true

tcm_store_maintenance:
    path:     /store/{storeid}/maintenance
    defaults: { _controller: AppBundle:Page:storeMaintenance }
    options:
        expose: true

tcm_update_sensors:
    path:     /store/{storeid}/sensors/update
    defaults: { _controller: AppBundle:Data:updateSensors }
    options:
        expose: true

tcm_store_maintenance_get:
    path:     /store/{storeid}/maintenance/get
    defaults: { _controller: AppBundle:Data:getStoreMaintenance }
    options:
        expose: true

tcm_collection_attachment_get:
    path:     /collection/attachment/{attachmentid}/get
    defaults: { _controller: CollectionBundle:Data:getCollectionAttachment }
    methods: [GET]
    options:
        expose: true
