# TCM home / dashboard
tcm_home:
    path:     /
    defaults: { _controller: AppBundle:Page:index }
    options:
        expose: true

tcm_profile_change_password:
    path:     /profile/change/password
    methods:  [POST]
    defaults: { _controller: UserBundle:Security:changePassword }
    options:
        expose: true
