# TCM home / dashboard
tcm_home:
    path:     /
    defaults: { _controller: AppBundle:Page:index }
    options:
        expose: true

tcm_profile_change_password:
    path:     /profile/change/password
    methods:  [POST]
    defaults: { _controller: UserBundle:Security:changePassword }
    options:
        expose: true

tcm_data_collector:
    path:     /data/collector
    #methods:  [PUT, POST]
    defaults: { _controller: DataCollectorBundle:Data:collectData }
    options:
        expose: true

tcm_data_collector_test:
    path:     /data/collector/test
    defaults: { _controller: DataCollectorBundle:Data:testPostData }
    options:
        expose: true
