# TCM splash
tcm_splash:
    path:     /
    defaults: { _controller: AppBundle:Page:splash }
    options:
        expose: true

tcm_dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Page:dashboard }
    options:
        expose: true

tcm_stores:
    path:     /stores
    defaults: { _controller: AppBundle:Page:stores }
    options:
        expose: true

tcm_stores_get:
    path:     /stores/get
    defaults: { _controller: AppBundle:Data:getStores }
    options:
        expose: true

tcm_store_get:
    path:     /store/{storeid}/get
    defaults: { _controller: AppBundle:Data:getStore }
    options:
        expose: true

tcm_store_show:
    path:     /store/{storeid}/show
    defaults: { _controller: AppBundle:Page:showStore }
    options:
        expose: true

tcm_update_sensors:
    path:     /store/{storeid}/sensors/update
    defaults: { _controller: AppBundle:Data:updateSensors }
    options:
        expose: true

tcm_logout:
    path:     /logout
    options:
        expose: true

tcm_profile_change_password:
    path:     /profile/change/password
    methods:  [POST]
    defaults: { _controller: UserBundle:Security:changePassword }
    options:
        expose: true

tcm_data_collector:
    path:     /data/collector
    methods:  [PUT, POST]
    defaults: { _controller: DataCollectorBundle:Data:collectData }
    options:
        expose: true

tcm_data_collector_test:
    path:     /data/collector/test
    defaults: { _controller: DataCollectorBundle:Data:testPostData }
    options:
        expose: true
