administration_dashboard:
    path:     /
    defaults: { _controller: AdministrationBundle:Page:dashboard }
    options:
        expose: true

#
# USERS
#
administration_users:
    path:     /users
    defaults: { _controller: AdministrationBundle:Page:users }
    options:
        expose: true

administration_users_get:
    path:     /users/get
    defaults: { _controller: UserBundle:Data:getUsers }
    methods: [GET]
    options:
        expose: true

administration_user_get:
    path:     /user/{userid}/get
    defaults: { _controller: UserBundle:Data:getUser }
    methods: [GET]
    options:
        expose: true

administration_user_edit:
    path:     /user/{userid}/edit
    defaults: { _controller: AdministrationBundle:Page:editUser }
    options:
        expose: true

administration_user_add:
    path:     /user/add
    defaults: { _controller: AdministrationBundle:Page:addUser }
    options:
        expose: true

administration_user_new:
    path:     /user/new
    defaults: { _controller: UserBundle:Data:newUser }
    methods: [GET]
    options:
        expose: true

administration_user_save:
    path:     /user/{userid}/save
    defaults: { _controller: UserBundle:Data:saveUser }
    methods: [POST, PUT]
    options:
        expose: true

administration_user_delete:
    path:     /user/{userid}/delete
    defaults: { _controller: UserBundle:Data:deleteUser }
    methods: [DELETE]
    options:
        expose: true

administration_user_delete_email:
    path:     /user/{userid}/email/{emailid}/delete
    defaults: { _controller: UserBundle:Data:deleteUserEmail }
    methods: [DELETE]
    options:
        expose: true

administration_user_delete_phone:
    path:     /user/{userid}/phone/{phoneid}/delete
    defaults: { _controller: UserBundle:Data:deleteUserPhone }
    methods: [DELETE]
    options:
        expose: true

administration_user_delete_address:
    path:     /user/{userid}/address/{addressid}/delete
    defaults: { _controller: UserBundle:Data:deleteUserAddress }
    methods: [DELETE]
    options:
        expose: true

administration_user_new_password:
    path:     /user/{userid}/new/password
    defaults: { _controller: UserBundle:Security:newPassword }
    methods: [POST, PUT]
    options:
        expose: true

#
# COMPANIES
#
administration_companies:
    path:     /companies
    defaults: { _controller: AdministrationBundle:Page:companies }
    options:
        expose: true

administration_companies_get:
    path:     /companies/get
    defaults: { _controller: CompanyBundle:Data:getCompanies }
    methods: [GET]
    options:
        expose: true

administration_company_get:
    path:     /company/{companyid}/get
    defaults: { _controller: CompanyBundle:Data:getCompany }
    methods: [GET]
    options:
        expose: true

administration_company_edit:
    path:     /company/{companyid}/edit
    defaults: { _controller: AdministrationBundle:Page:editCompany }
    options:
        expose: true

administration_company_add:
    path:     /company/add
    defaults: { _controller: AdministrationBundle:Page:addCompany }
    options:
        expose: true

administration_company_new:
    path:     /company/new
    defaults: { _controller: CompanyBundle:Data:newCompany }
    methods: [GET]
    options:
        expose: true

administration_company_save:
    path:     /company/{companyid}/save
    defaults: { _controller: CompanyBundle:Data:saveCompany }
    methods: [POST, PUT]
    options:
        expose: true

administration_company_delete:
    path:     /company/{companyid}/delete
    defaults: { _controller: CompanyBundle:Data:deleteCompany }
    methods: [DELETE]
    options:
        expose: true

administration_company_delete_email:
    path:     /company/{companyid}/email/{emailid}/delete
    defaults: { _controller: CompanyBundle:Data:deleteCompanyEmail }
    methods: [DELETE]
    options:
        expose: true

administration_company_delete_phone:
    path:     /company/{companyid}/phone/{phoneid}/delete
    defaults: { _controller: CompanyBundle:Data:deleteCompanyPhone }
    methods: [DELETE]
    options:
        expose: true

administration_company_delete_address:
    path:     /company/{companyid}/address/{addressid}/delete
    defaults: { _controller: CompanyBundle:Data:deleteCompanyAddress }
    methods: [DELETE]
    options:
        expose: true

#
# REGIONS
#
administration_regions:
    path:     /regions
    defaults: { _controller: AdministrationBundle:Page:regions }
    options:
        expose: true

administration_regions_get:
    path:     /regions/get
    defaults: { _controller: CompanyBundle:Data:getRegions }
    methods: [GET]
    options:
        expose: true

administration_region_get:
    path:     /region/{regionid}/get
    defaults: { _controller: CompanyBundle:Data:getRegion }
    methods: [GET]
    options:
        expose: true

administration_region_edit:
    path:     /region/{regionid}/edit
    defaults: { _controller: AdministrationBundle:Page:editRegion }
    options:
        expose: true

administration_region_add:
    path:     /region/add
    defaults: { _controller: AdministrationBundle:Page:addRegion }
    options:
        expose: true

administration_region_new:
    path:     /region/new
    defaults: { _controller: CompanyBundle:Data:newRegion }
    methods: [GET]
    options:
        expose: true

administration_region_save:
    path:     /region/{regionid}/save
    defaults: { _controller: CompanyBundle:Data:saveRegion }
    methods: [POST, PUT]
    options:
        expose: true

administration_region_delete:
    path:     /region/{regionid}/delete
    defaults: { _controller: CompanyBundle:Data:deleteRegion }
    methods: [DELETE]
    options:
        expose: true

#
# STORES
#
administration_stores:
    path:     /stores
    defaults: { _controller: AdministrationBundle:Page:stores }
    options:
        expose: true

administration_stores_get:
    path:     /stores/get
    defaults: { _controller: StoreBundle:Data:getStores }
    methods: [GET]
    options:
        expose: true

administration_store_get:
    path:     /store/{storeid}/get
    defaults: { _controller: StoreBundle:Data:getStore }
    methods: [GET]
    options:
        expose: true

administration_store_edit:
    path:     /store/{storeid}/edit
    defaults: { _controller: AdministrationBundle:Page:editStore }
    options:
        expose: true

administration_store_add:
    path:     /store/add
    defaults: { _controller: AdministrationBundle:Page:addStore }
    options:
        expose: true

administration_store_new:
    path:     /store/new
    defaults: { _controller: StoreBundle:Data:newStore }
    methods: [GET]
    options:
        expose: true

administration_store_save:
    path:     /store/{storeid}/save
    defaults: { _controller: StoreBundle:Data:saveStore }
    methods: [POST, PUT]
    options:
        expose: true

administration_store_delete:
    path:     /store/{storeid}/delete
    defaults: { _controller: StoreBundle:Data:deleteStore }
    methods: [DELETE]
    options:
        expose: true

administration_store_delete_email:
    path:     /store/{storeid}/email/{emailid}/delete
    defaults: { _controller: StoreBundle:Data:deleteStoreEmail }
    methods: [DELETE]
    options:
        expose: true

administration_store_delete_phone:
    path:     /store/{storeid}/phone/{phoneid}/delete
    defaults: { _controller: StoreBundle:Data:deleteStorePhone }
    methods: [DELETE]
    options:
        expose: true

administration_store_delete_address:
    path:     /store/{storeid}/address/{addressid}/delete
    defaults: { _controller: StoreBundle:Data:deleteStoreAddress }
    methods: [DELETE]
    options:
        expose: true

#
# MAINTENANCE
#
administration_maintenance:
    path:     /maintenance/stores
    defaults: { _controller: AdministrationBundle:Page:maintenanceStores }
    options:
        expose: true

administration_maintenance_stores_get:
    path:     /maintenance/stores/get
    defaults: { _controller: StoreBundle:Data:getStores }
    methods: [GET]
    options:
        expose: true

administration_maintenance_store:
    path:     /maintenance/store/{storeid}/get
    defaults: { _controller: AdministrationBundle:Page:maintenanceStore }
    methods: [GET]
    options:
        expose: true

administration_maintenance_store_get:
    path:     /maintenance/store/{storeid}/maintenance/get
    defaults: { _controller: CollectionBundle:Data:getStoreMaintenance }
    options:
        expose: true

#
# INVENTORY
#
administration_inventory:
    path:     /inventory/stores
    defaults: { _controller: AdministrationBundle:Page:inventoryStores }
    options:
        expose: true

administration_inventory_stores_get:
    path:     /inventory/stores/get
    defaults: { _controller: StoreBundle:Data:getStores }
    methods: [GET]
    options:
        expose: true

administration_inventory_store:
    path:     /inventory/store/{storeid}/get
    defaults: { _controller: AdministrationBundle:Page:inventoryStore }
    methods: [GET]
    options:
        expose: true

administration_inventory_store_get:
    path:     /inventory/store/{storeid}/inventory/get
    defaults: { _controller: CollectionBundle:Data:getStoreInventory }
    options:
        expose: true

#
# COLLECTIONS (GENERAL)
#
administration_collection_save:
    path:     /collection/{collectionid}/save
    defaults: { _controller: CollectionBundle:Data:saveCollection }
    methods: [POST, PUT]
    options:
        expose: true

administration_collection_delete:
    path:     /collection/{collectionid}/delete
    defaults: { _controller: CollectionBundle:Data:deleteCollection }
    methods: [DELETE]
    options:
        expose: true

administration_collection_upload:
    path:     /collection/{collectionid}/upload
    defaults: { _controller: CollectionBundle:Data:uploadCollection }
    methods: [POST]
    options:
        expose: true

administration_collection_attachment_get:
    path:     /collection/attachment/{attachmentid}/get
    defaults: { _controller: CollectionBundle:Data:getCollectionAttachment }
    methods: [GET]
    options:
        expose: true

administration_collection_attachment_delete:
    path:     /collection/{collectionid}/attachment/{attachmentid}/delete
    defaults: { _controller: CollectionBundle:Data:deleteCollectionAttachment }
    methods: [DELETE]
    options:
        expose: true

#
# NOTIFICATIONS
#
administration_open_notifications:
    path:     /notifications/open
    defaults: { _controller: AdministrationBundle:Page:openNotifications }
    options:
        expose: true

administration_open_notifications_get:
    path:     /notifications/open/get
    defaults: { _controller: NotificationBundle:Data:getOpenNotifications }
    options:
        expose: true

administration_closed_notifications:
    path:     /notifications/closed
    defaults: { _controller: AdministrationBundle:Page:closedNotifications }
    options:
        expose: true

administration_closed_input_notifications_get:
    path:     /notifications/closed/inputs/get
    defaults: { _controller: NotificationBundle:Data:getClosedInputNotifications }
    options:
        expose: true

administration_closed_temperature_notifications_get:
    path:     /notifications/closed/temperatures/get
    defaults: { _controller: NotificationBundle:Data:getClosedTemperatureNotifications }
    options:
        expose: true

administration_handle_input_notification:
    path:     /notifications/input/{notificationid}/handle
    defaults: { _controller: NotificationBundle:Data:handleInputNotification }
    options:
        expose: true

administration_handle_temperature_notification:
    path:     /notifications/temperature/{notificationid}/handle
    defaults: { _controller: NotificationBundle:Data:handleTemperatureNotification }
    options:
        expose: true

#
# CONFIGURATION STORES
#
configuration_stores:
    path:     /configuration/stores
    defaults: { _controller: AdministrationBundle:Page:configurationStores }
    methods: [GET]
    options:
        expose: true

configuration_stores_get:
    path:     /configuration/stores/get
    defaults: { _controller: DeviceBundle:Data:getStores }
    methods: [GET]
    options:
        expose: true

configuration_store_get:
    path:     /configuration/store/{storeid}/get
    defaults: { _controller: DeviceBundle:Data:getStore }
    methods: [GET]
    options:
        expose: true

configuration_store_edit:
    path:     /configuration/store/{storeid}/edit
    defaults: { _controller: AdministrationBundle:Page:editConfigurationStore }
    options:
        expose: true

configuration_store_save:
    path:     /configuration/store/{storeid}/save
    defaults: { _controller: DeviceBundle:Data:saveStore }
    methods: [POST, PUT]
    options:
        expose: true

#
# INSTALLATION
#
configuration_installation:
    path:     /installation/sensors
    defaults: { _controller: AdministrationBundle:Page:installationSensors }
    methods: [GET]
    options:
        expose: true

installation_sensors_get:
    path:     /installation/sensors/get
    defaults: { _controller: DeviceBundle:Data:getSensors }
    methods: [GET]
    options:
        expose: true

installation_sensor_get:
    path:     /installation/sensor/{sensorid}/type/{typeid}/get
    defaults: { _controller: DeviceBundle:Data:getSensor }
    methods: [GET]
    options:
        expose: true

installation_sensor_edit:
    path:     /installation/sensor/{sensorid}/type/{typeid}/edit
    defaults: { _controller: AdministrationBundle:Page:editSensor }
    options:
        expose: true

installation_sensor_save:
    path:     /installation/sensor/{sensorid}/type/{typeid}/save
    defaults: { _controller: DeviceBundle:Data:saveSensor }
    methods: [POST, PUT]
    options:
        expose: true
