services:
   collection_helper:
        class: CollectionBundle\Services\CollectionHelper
        arguments: ['@service_container']

   class_helper:
        class: AppBundle\Services\ClassHelper
        arguments: ['@service_container']